---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: blazor-on-tap
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: blazor-on-tap
    apps.tanzu.vmware.com/has-tests: "true"
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: blazor-on-tap
    tanzu.app.live.view.application.actuator.port: "9090"
spec:
  build:
    env:
    - name: DOTNET_CLI_TELEMETRY_OPTOUT
      value: "true"
    - name: BP_DOTNET_PROJECT_PATH
      value: "./Server"
    - name: BP_DOTNET_PUBLISH_FLAGS
      value: "--self-contained=true"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  env:
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: "true"

  source:
    git:
      url: https://github.com/franktylerva/blazor-on-tap.git
      ref:
        branch: main
        
  serviceClaims:
    - name: blazor-on-tap-sso
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: blazor-on-tap-sso
        
  # serviceClaims:
  #   - name: database
  #     ref:
  #       apiVersion: services.apps.tanzu.vmware.com/v1alpha1
  #       kind: ResourceClaim
  #       name: customer-database-claim
